language: csharp
mono: none
dist: xenial
dotnet: 2.2

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
    - WORKING_DIR=src/PK.OrchardCore.Website
  
install:
 - cd $WORKING_DIR
 - dotnet restore

script:
 - dotnet build